name = "mailstatus"
main = "src/index.ts"
compatibility_date = "2023-02-11"
account_id = "fc50728782db5601b969d9a65dc24fd6"
kv_namespaces = [
  { binding = "KV", id = "f674a320937d423589b0c00d4c8a109b", preview_id = "5125f329d61249d79a05e57e08c7dc6e" }
]

[triggers]
crons = [ "0/5 * * * *" ]

[env.test]
name = "mailstatus-test"
kv_namespaces = [
  { binding = "KV", id = "2bb6819456a14eeab7862bc2fb889c01", preview_id = "b7b4e380fccf41fda30a09e0b1e772c5" }
]
